### PR TITLE
Handle Implicit Object Creation in return values.

### PR DESCRIPTION
**Pull request by JeremyMorton**

### CODE REVIEW

**Comment by JohanLarsson** [comment]
Do you have more things lined up or should we release now?

**Comment by JeremyMorton** [comment]
This, and GuOrg/Gu.Roslyn.Extensions#210 are all that I had for this.

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/IDisposableAnalyzers/4.0.7

**Comment by JeremyMorton** [comment]
Can you pull https://github.com/GuOrg/Gu.Roslyn.Extensions/pull/210 into this?

**Comment by JohanLarsson** [comment]
Yep

**Pull request merged**
